package main

import (
	"bytes"
	"image"
	"image/jpeg"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func queueTestApp(t *testing.T) *App {
	t.Helper()
	dir := t.TempDir()
	app := &App{settings: Settings{DataDir: dir, UploadDir: filepath.Join(dir, "receipts"), MaxUploadBytes: 1024 * 1024, SecretKey: "test"}, uploadTok: "secret"}
	if err := initDB(app.settings.dbPath()); err != nil {
		t.Fatal(err)
	}
	if err := execSQL(app.settings.dbPath(), "INSERT INTO cardholders(name) VALUES ('Person'); INSERT INTO stores(name) VALUES ('Store')"); err != nil {
		t.Fatal(err)
	}
	return app
}
func queueRequest(t *testing.T, app *App, data []byte, cardholder string) *httptest.ResponseRecorder {
	t.Helper()
	return queueFilesRequest(t, app, [][]byte{data}, []string{"original.jpg"}, cardholder)
}

func queueFilesRequest(t *testing.T, app *App, files [][]byte, names []string, cardholder string) *httptest.ResponseRecorder {
	t.Helper()
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	for key, value := range map[string]string{"cardholder_id": cardholder, "total": "19.08", "purchase_location": "Vendor", "store_ids": "1", "description": "Milk"} {
		if err := writer.WriteField(key, value); err != nil {
			t.Fatal(err)
		}
	}
	for i, data := range files {
		part, err := writer.CreateFormFile("files", names[i])
		if err != nil {
			t.Fatal(err)
		}
		if _, err := part.Write(data); err != nil {
			t.Fatal(err)
		}
	}
	writer.Close()
	r := httptest.NewRequest("POST", "/upload/secret", &body)
	r.Header.Set("Content-Type", writer.FormDataContentType())
	w := httptest.NewRecorder()
	app.upload(w, r)
	return w
}
func jobState(t *testing.T, app *App) (string, string) {
	t.Helper()
	db, err := openDB(app.settings.dbPath())
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	var id, state string
	if err := db.QueryRow("SELECT id,status FROM receipt_jobs").Scan(&id, &state); err != nil {
		t.Fatal(err)
	}
	return id, state
}
func TestQueuedReceiptLifecycle(t *testing.T) {
	app := queueTestApp(t)
	var photo bytes.Buffer
	jpeg.Encode(&photo, image.NewRGBA(image.Rect(0, 0, 10, 20)), nil)
	w := queueRequest(t, app, photo.Bytes(), "1")
	if w.Code != 200 || !strings.Contains(w.Body.String(), "Processing is queued") {
		t.Fatalf("upload: %d %s", w.Code, w.Body.String())
	}
	id, state := jobState(t, app)
	if state != "queued" {
		t.Fatal(state)
	}
	if _, err := os.Stat(filepath.Join(app.settings.UploadDir, id+".pdf")); !os.IsNotExist(err) {
		t.Fatal("PDF generated by web process")
	}
	view, err := loadAdminView(app.settings)
	if err != nil || len(view.Uploads) != 0 {
		t.Fatal("pending PDF visible", err)
	}
	// Metadata was captured at upload time, so deletion while queued is safe.
	if err := execSQL(app.settings.dbPath(), "DELETE FROM cardholders; DELETE FROM stores"); err != nil {
		t.Fatal(err)
	}
	worked, err := processNextJob(app.settings)
	if err != nil || !worked {
		t.Fatal(worked, err)
	}
	_, state = jobState(t, app)
	if state != "completed" {
		t.Fatal(state)
	}
	view, err = loadAdminView(app.settings)
	if err != nil || len(view.Uploads) != 1 || view.Uploads[0].CardholderName != "Person" || view.Uploads[0].StoreNames != "Store" {
		t.Fatal(view, err)
	}
	pdf, err := os.ReadFile(filepath.Join(app.settings.UploadDir, id+".pdf"))
	if err != nil || !bytes.HasPrefix(pdf, []byte("%PDF-")) {
		t.Fatal("missing PDF", err)
	}
	if _, err := os.Stat(filepath.Join(app.settings.queueDir(), id)); !os.IsNotExist(err) {
		t.Fatal("sources not cleaned")
	}
	worked, err = processNextJob(app.settings)
	if worked || err != nil {
		t.Fatal("completed job ran twice", worked, err)
	}
}
func TestFailedReceiptRetryAndRecovery(t *testing.T) {
	app := queueTestApp(t)
	if w := queueRequest(t, app, []byte("invalid image"), "1"); w.Code != 200 {
		t.Fatal(w.Code)
	}
	id, _ := jobState(t, app)
	if _, err := processNextJob(app.settings); err != nil {
		t.Fatal(err)
	}
	_, state := jobState(t, app)
	if state != "failed" {
		t.Fatal(state)
	}
	r := httptest.NewRequest("GET", "/admin/jobs", nil)
	r.AddCookie(&http.Cookie{Name: sessionCookie, Value: signSession("test")})
	w := httptest.NewRecorder()
	app.jobsStatus(w, r)
	if !strings.Contains(w.Body.String(), "failed") || !strings.Contains(w.Body.String(), "Retry") {
		t.Fatal(w.Body.String())
	}
	r = httptest.NewRequest("POST", "/admin/jobs/"+id+"/retry", nil)
	w = httptest.NewRecorder()
	app.retryJob(w, r)
	if w.Code != 401 {
		t.Fatal("retry unprotected")
	}
	r.AddCookie(&http.Cookie{Name: sessionCookie, Value: signSession("test")})
	w = httptest.NewRecorder()
	app.retryJob(w, r)
	if w.Code != 303 {
		t.Fatal(w.Code)
	}
	var photo bytes.Buffer
	jpeg.Encode(&photo, image.NewRGBA(image.Rect(0, 0, 10, 20)), nil)
	if err := os.WriteFile(filepath.Join(app.settings.queueDir(), id, "000000"), photo.Bytes(), 0600); err != nil {
		t.Fatal(err)
	}
	// Simulate an interrupted conversion, then the restart recovery query.
	if err := execSQL(app.settings.dbPath(), "UPDATE receipt_jobs SET status='processing'"); err != nil {
		t.Fatal(err)
	}
	if err := execSQL(app.settings.dbPath(), "UPDATE receipt_jobs SET status='queued',updated_at=? WHERE status='processing'", nowISO()); err != nil {
		t.Fatal(err)
	}
	if _, err := processNextJob(app.settings); err != nil {
		t.Fatal(err)
	}
	_, state = jobState(t, app)
	if state != "completed" {
		t.Fatal(state)
	}
	db, _ := openDB(app.settings.dbPath())
	defer db.Close()
	var count int
	db.QueryRow("SELECT COUNT(*) FROM uploads").Scan(&count)
	if count != 1 {
		t.Fatal("duplicate receipt", count)
	}
}
func TestRejectedUploadCleanup(t *testing.T) {
	for _, tc := range []struct {
		name, cardholder string
		limit            int64
	}{{"invalid cardholder", "999", 1024 * 1024}, {"oversize", "1", 5}} {
		t.Run(tc.name, func(t *testing.T) {
			app := queueTestApp(t)
			app.settings.MaxUploadBytes = tc.limit
			if w := queueRequest(t, app, []byte("image bytes"), tc.cardholder); w.Code != 400 {
				t.Fatal(w.Code)
			}
			entries, err := os.ReadDir(app.settings.queueDir())
			if err != nil || len(entries) != 0 {
				t.Fatal("partial upload retained", entries, err)
			}
			db, _ := openDB(app.settings.dbPath())
			defer db.Close()
			var count int
			db.QueryRow("SELECT COUNT(*) FROM receipt_jobs").Scan(&count)
			if count != 0 {
				t.Fatal(count)
			}
			db.QueryRow("SELECT COUNT(*) FROM uploads").Scan(&count)
			if count != 0 {
				t.Fatal(count)
			}
		})
	}
}

func TestClearFailedJob(t *testing.T) {
	app := queueTestApp(t)
	if w := queueRequest(t, app, []byte("invalid image"), "1"); w.Code != 200 {
		t.Fatal(w.Code)
	}
	id, _ := jobState(t, app)
	clear := func(auth bool, method string) int {
		r := httptest.NewRequest(method, "/admin/jobs/"+id+"/clear", nil)
		if auth {
			r.AddCookie(&http.Cookie{Name: sessionCookie, Value: signSession("test")})
		}
		w := httptest.NewRecorder()
		app.retryJob(w, r)
		return w.Code
	}
	if code := clear(false, "POST"); code != 401 {
		t.Fatal(code)
	}
	if code := clear(true, "GET"); code != 405 {
		t.Fatal(code)
	}
	if code := clear(true, "POST"); code != 303 {
		t.Fatal(code)
	}
	if _, state := jobState(t, app); state != "queued" {
		t.Fatal("cleared queued job", state)
	}
	if _, err := processNextJob(app.settings); err != nil {
		t.Fatal(err)
	}
	if code := clear(true, "POST"); code != 303 {
		t.Fatal(code)
	}
	if _, err := os.Stat(filepath.Join(app.settings.queueDir(), id)); !os.IsNotExist(err) {
		t.Fatal("sources remain", err)
	}
	db, err := openDB(app.settings.dbPath())
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	for _, table := range []string{"receipt_jobs", "uploads", "receipt_stores"} {
		var count int
		if err := db.QueryRow("SELECT COUNT(*) FROM " + table).Scan(&count); err != nil || count != 0 {
			t.Fatalf("%s: count=%d err=%v", table, count, err)
		}
	}
	if code := clear(true, "POST"); code != 303 {
		t.Fatal("repeat clear", code)
	}
}

func TestPDFUploadPreservesDownloadedBytes(t *testing.T) {
	app := queueTestApp(t)
	// Any attempted image conversion must fail in this test.
	t.Setenv("PATH", t.TempDir())
	var original bytes.Buffer
	var photo bytes.Buffer
	if err := jpeg.Encode(&photo, image.NewRGBA(image.Rect(0, 0, 10, 20)), nil); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "receipt.pdf")
	if err := writePDF([]PdfImage{{JPEG: photo.Bytes(), Width: 10, Height: 20}}, path); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	original.Write(data)
	w := queueFilesRequest(t, app, [][]byte{original.Bytes()}, []string{"receipt.PDF"}, "1")
	if w.Code != http.StatusOK {
		t.Fatalf("upload: %d %s", w.Code, w.Body.String())
	}
	id, _ := jobState(t, app)
	if worked, err := processNextJob(app.settings); !worked || err != nil {
		t.Fatal(worked, err)
	}
	if _, state := jobState(t, app); state != "completed" {
		t.Fatal(state)
	}
	stored, err := os.ReadFile(filepath.Join(app.settings.UploadDir, id+".pdf"))
	if err != nil || !bytes.Equal(stored, original.Bytes()) {
		t.Fatal("stored PDF differs from upload", err)
	}
	view, err := loadAdminView(app.settings)
	if err != nil || len(view.Uploads) != 1 {
		t.Fatal(view, err)
	}
	r := httptest.NewRequest("GET", "/admin/uploads/1/download", nil)
	r.AddCookie(&http.Cookie{Name: sessionCookie, Value: signSession("test")})
	w = httptest.NewRecorder()
	app.uploadAction(w, r)
	if w.Code != http.StatusOK || !bytes.Equal(w.Body.Bytes(), original.Bytes()) {
		t.Fatalf("download changed PDF: status %d", w.Code)
	}
	if got := w.Header().Get("Content-Disposition"); !strings.Contains(got, "-vendor-19.08-milk-blank-store.pdf") || strings.Contains(got, "receipt.PDF") {
		t.Fatal("download filename", got)
	}
	if _, err := os.Stat(filepath.Join(app.settings.queueDir(), id)); !os.IsNotExist(err) {
		t.Fatal("PDF source not cleaned up", err)
	}
}

func TestRejectPDFWithOtherFiles(t *testing.T) {
	for _, other := range [][]byte{[]byte("image"), []byte("%PDF-1.4\nother")} {
		app := queueTestApp(t)
		w := queueFilesRequest(t, app, [][]byte{[]byte("%PDF-1.4\nreceipt"), other}, []string{"receipt.pdf", "other"}, "1")
		if w.Code != http.StatusBadRequest || !strings.Contains(w.Body.String(), "one PDF on its own") {
			t.Fatalf("upload: %d %s", w.Code, w.Body.String())
		}
		entries, err := os.ReadDir(app.settings.queueDir())
		if err != nil || len(entries) != 0 {
			t.Fatal("rejected files retained", entries, err)
		}
		view, err := loadAdminView(app.settings)
		if err != nil || len(view.Uploads) != 0 {
			t.Fatal("rejected receipt visible", view, err)
		}
	}
}
